repository_type: pipeline
lint:
  files_exist:
    - conf/test.config # We skip these linting as we have splitted tests between targeted and screening
  files_unchanged:
    - lib/NfcoreTemplate.groovy # Introduced a change ahead of the nf-core/tools release
