name: nf-core CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]

env:
  NXF_ANSI_LOG: false

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Run pipeline with test data
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/crisprseq') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "23.04.0"
          - "latest-everything"
        ANALYSIS:
          - "test_screening"
          - "test_screening_paired"
          - "test_screening_rra"
          - "test_targeted"
          - "test_umis"
          - "test_screening_count_table"
        profile: ["docker", "singularity", "conda"]
      fail-fast: false # run all tests even if one fails

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Set up Singularity
        if: matrix.profile == 'singularity'
        uses: eWaterCycle/setup-singularity@931d4e31109e875b13309ae1d07c70ca8fbc8537 # v7
        with:
          singularity-version: 3.8.3

      - name: Singularity mount HOME
        if: matrix.profile == 'singularity'
        run: echo "NXF_SINGULARITY_HOME_MOUNT=true" >> $GITHUB_ENV

      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@a4260408e20b96e80095f42ff7f1a15b27dd94ca # v3
        with:
          miniconda-version: "latest"
          channels: conda-forge,bioconda,defaults

      - name: Conda setup
        run: |
          conda clean -a
          conda install -n base conda-libmamba-solver
          conda config --set solver libmamba
          echo $(realpath $CONDA)/condabin >> $GITHUB_PATH
          echo $(realpath python) >> $GITHUB_PATH

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Disk space cleanup
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1

      - name: Run pipeline with test data (${{ matrix.ANALYSIS }} - ${{ matrix.profile }})
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile ${{ matrix.ANALYSIS }},${{ matrix.profile }} --outdir ./results_${{ matrix.ANALYSIS }}_${{ matrix.profile }}
